### ISSUE TITLE
Final Capstone Project - Kanban Board

### ISSUE THREAD

**Issue by meryemsanem** [meryemsanem/final-capstone-back-end#17]
**Hi,
There are 5 people in our group:** 

- @meryemsanem 
- @abdozayan12 
- @yin-ka 
- @ClarenceAtim 
- @yemidada

**Here is the [link](https://github.com/meryemsanem/final-capstone-back-end/projects/1) for the GitHub Project.**

**Here is the inital screenshot of the Kanban Board:**
![kanban](https://github.com/meryemsanem/final-capstone-back-end/assets/82718562/135a04c3-6cc8-4814-a12b-964653967c82)

**Comment by Meltrust** [comment]
Hi @meryemsanem,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have assignees, descriptions, and pointings according to spec. ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
